apiVersion: v1
kind: Service
metadata:
  name: dependent-app-service
  namespace: test-ns
spec:
  clusterIP: None  # Headless service requirement
  selector:
    app: dependent-app
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dependent-app
  namespace: test-ns
spec:
  serviceName: dependent-app-service  # References the service above
  replicas: 1
  selector:
    matchLabels:
      app: dependent-app
  template:
    metadata:
      labels:
        app: dependent-app
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values: ["desired-zone-for-affinity"]
            topologyKey: "topology.kubernetes.io/zone"
      containers:
      - name: main-app
        image: nginx:alpine
        command: ["sh", "-c"]
        args: ["sleep 5 && while :; do echo '15^999999' | bc >/dev/null; done"]
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
