apiVersion: v1
kind: Namespace
metadata:
  name: e2e-admin-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: e2e-test-sa
  namespace: e2e-admin-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: e2e-test-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "namespaces", "persistentvolumes", "services"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "get"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["*"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["*"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: e2e-test-binding
subjects:
  - kind: ServiceAccount
    name: e2e-test-sa
    namespace: e2e-admin-ns
roleRef:
  kind: ClusterRole
  name: e2e-test-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: e2e-cluster-tester-cronjob
  namespace: e2e-admin-ns
spec:
  schedule: "0 */6 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: e2e-test-sa
          containers:
            - name: e2e-test-runner
              image: antonbiz/cluster-tester-debug:1.9
              imagePullPolicy: Always
          restartPolicy: Never
