apiVersion: v1
kind: ServiceAccount
metadata:
  name: e2e-test-sa
  namespace: default  # or your preferred namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: e2e-test-role
rules:
  # Full access (*) on pods, pods/log, namespaces, and persistentvolumes
  - apiGroups: [""]
    resources: ["pods", "pods/log", "namespaces", "persistentvolumes"]
    verbs: ["*"]
  # Restricted to only "list" on nodes
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list"]
  # Full access (*) on deployments and statefulsets in the apps API group
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["*"]
  # Full access (*) on poddisruptionbudgets in the policy API group
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["*"]
  # Full access (*) on horizontalpodautoscalers in the autoscaling API group
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: e2e-test-binding
subjects:
  - kind: ServiceAccount
    name: e2e-test-sa
    namespace: default  # match SA namespace above
roleRef:
  kind: ClusterRole
  name: e2e-test-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cluster-e2e-tester-cronjob
  namespace: default # or your preferred namespace
spec:
  schedule: "0 */6 * * *" # every 6 hours, adjust as needed
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: e2e-test-sa
          containers:
            - name: e2e-test-runner
              image: antonbiz/cluster-tester-debug:1.1
              imagePullPolicy: Always
              env:
                - name: ACCESS_MODE
                  value: "LOCAL_K8S_API"
          restartPolicy: Never
