apiVersion: v1
kind: Namespace
metadata:
  name: e2e-admin-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: e2e-test-sa
  namespace: e2e-admin-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: e2e-test-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "namespaces", "persistentvolumes", "services"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "get"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["*"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["*"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: e2e-test-binding
subjects:
  - kind: ServiceAccount
    name: e2e-test-sa
    namespace: e2e-admin-ns
roleRef:
  kind: ClusterRole
  name: e2e-test-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: cluster-tester-debug-pod
  namespace: e2e-admin-ns
spec:
  serviceAccountName: e2e-test-sa  # Matches ServiceAccount below
  containers:
  - name: debug-container
    image: antonbiz/cluster-tester-debug:1.10
    command: ["/busybox/sh", "-c", "sleep infinity & wait"]
    imagePullPolicy: Always
    securityContext:
      runAsUser: 65534
      runAsGroup: 65534
  restartPolicy: Never
---
