apiVersion: v1
kind: ServiceAccount
metadata:
  name: e2e-test-sa
  namespace: default  # or your preferred namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: e2e-test-role
rules:
  # Full access (*) on pods, pods/log, namespaces, and persistentvolumes
  - apiGroups: [""]
    resources: ["pods", "pods/log", "namespaces", "persistentvolumes"]
    verbs: ["*"]
  # Restricted to only "list" on nodes
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list"]
  # Full access (*) on deployments and statefulsets in the apps API group
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["*"]
  # Full access (*) on poddisruptionbudgets in the policy API group
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["*"]
  # Full access (*) on horizontalpodautoscalers in the autoscaling API group
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: e2e-test-binding
subjects:
  - kind: ServiceAccount
    name: e2e-test-sa
    namespace: default  # match SA namespace above
roleRef:
  kind: ClusterRole
  name: e2e-test-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: cluster-tester-debug-pod
spec:
  serviceAccountName: e2e-test-sa  # Matches ServiceAccount below
  containers:
  - name: debug-container
    image: antonbiz/cluster-tester-debug:1.5
    command: ["/busybox/sh", "-c", "sleep infinity & wait"]
    imagePullPolicy: Always
    securityContext:
      runAsUser: 65534
      runAsGroup: 65534
  restartPolicy: Never
---
