apiVersion: apps/v1
kind: Deployment
metadata:
  name: zone-spread-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: myapp
      containers:
      - name: app-container
        image: nginx:alpine
        resources:
          requests:
            cpu: 200m  # Required for HPA CPU metrics
