apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: test-ns
spec:
  replicas: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 6       # No limit 
      maxUnavailable: 6 # Allow all pods to be unaviailable to check if PDB keeps up this limit
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
        component: my-unique-deployment  # Added unique label
    spec:
      containers:
      - name: main-app
        image: nginx:alpine
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"