apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: test-ns
spec:
  replicas: 12
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: main-app
        image: nginx:alpine
        # command: ["sh", "-c"]
        # args: ["sleep 5 && while :; do echo '15^999999' | bc >/dev/null; done"]
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"