# Base deployment constrained to specific zone
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zone-marker
  namespace: test-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desired-zone-for-affinity
  template:
    metadata:
      labels:
        app: desired-zone-for-affinity
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        command: ["sh", "-c"]
        args: ["sleep 5 && while :; do echo '15^999999' | bc >/dev/null; done"]
        resources:
          requests:
            cpu: "10m"
            memory: "16Mi"
