apiVersion: v1
kind: Service
metadata:
  name: dependent-app-service
  namespace: test-ns
spec:
  clusterIP: None
  selector:
    app: dependent-app
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app
  namespace: test-ns
spec:
  serviceName: dependent-app-service
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  minReadySeconds: 10
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: main-app
        image: nginx:alpine
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
        volumeMounts:
        - name: app-data
          mountPath: /data
      volumes:
      - name: app-data
        emptyDir:
          sizeLimit: 1Mi
