apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: app-pdb
  namespace: test-ns
spec:
  minAvailable: 5
  selector:
    matchLabels:
      app: sts-app               
      component: my-unique-sts
