apiVersion: v1
kind: Service
metadata:
  name: dependent-app-service
  namespace: test-ns
spec:
  clusterIP: None
  selector:
    app: sts-app

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app
  namespace: test-ns
spec:
  serviceName: dependent-app-service
  replicas: 6
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: sts-app  
  template:
    metadata:
      labels:
        app: sts-app
        component: my-unique-sts
    spec:
      containers:
      - name: main-app
        image: nginx:alpine
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
        volumeMounts:
        - name: app-data
          mountPath: /data
      volumes:
      - name: app-data
        emptyDir:
          sizeLimit: 1Mi